spring:
  profiles:
    active: local


oauth:
  kakao:
    client-id: 6faf123f48006a1b2913c7ac40b738d0
    client-secret :
    authorization-server-url: https://kauth.kakao.com/oauth/token
    api-server-url: https://kapi.kakao.com/v2/user/me

  naver:
    client-id: RZnRn6PC60FO_YfLHWmK
    client-secret: XYJdg26nT5
    authorization-server-url: https://nid.naver.com/oauth2.0/token
    api-server-url: https://openapi.naver.com/v1/nid/me

  facebook:
    client-id: 674473653805473
    client-secret: dd0a8dc92c58f45c25406aa8509a4099
    authorization-server-url: https://graph.facebook.com/v13.0/oauth/access_token
    api-server-url: https://graph.facebook.com/v13.0/me